[package]
name = "web_crawler_demo"
version = "0.1.0"
authors = ["Archibald Neil MacDonald <archibladnmac@gamil.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
select="^0.5.0"
reqwest="^0.11.0"
futures = "0.3"